# Generated by Django 5.1.3 on 2024-11-19 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='end_year',
            new_name='exam_date',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='test',
        ),
        migrations.AddField(
            model_name='examination',
            name='exam_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
