# Generated by Django 5.1.3 on 2024-12-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_studentresult_marksheet_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='examination',
        ),
        migrations.AddField(
            model_name='student',
            name='examinations',
            field=models.ManyToManyField(related_name='students', to='main_app.examination'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='marksheet_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
