# Generated by Django 5.1.3 on 2024-12-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_student_examination_student_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Chair'), (2, 'Teacher'), (3, 'Student')], default=1, max_length=1),
        ),
    ]
