# Generated by Django 5.1.2 on 2024-11-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("make_pdf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.ImageField(blank=True, upload_to="")),
            ],
        ),
    ]
