# Generated by Django 5.1.2 on 2024-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("make_pdf", "0002_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.ImageField(blank=True, upload_to="test_paper"),
        ),
    ]
