# Generated by Django 5.1.2 on 2024-11-20 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("make_pdf", "0003_alter_submission_grade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="grade",
            new_name="paper",
        ),
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
