# Generated by Django 5.1.2 on 2024-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("make_pdf", "0005_alter_submission_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="name",
            field=models.CharField(default="Unnamed", max_length=100),
        ),
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
