# Generated by Django 5.1.3 on 2024-11-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='receiver_student',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sender_teacher',
        ),
    ]
