# Generated by Django 5.1.3 on 2024-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_studentresult_marksheet_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='marksheet_pic',
            field=models.ImageField(blank=True, null=True, upload_to='marksheets/'),
        ),
    ]
