# Generated by Django 5.1.3 on 2024-12-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_student_examination_student_examinations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='examinations',
        ),
        migrations.AddField(
            model_name='student',
            name='examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.examination'),
        ),
    ]
